src/api/PromoCodeFactory/PromoCodeFactory.WebMVC/Models/ErrorViewModel.cs
using System;

namespace PromoCodeFactory.WebMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/api/PromoCodeFactory/PromoCodeFactory.WebMVC/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PromoCodeFactory.BusinessLogic.Interfaces.PromoCodeManagementServices;

namespace PromoCodeFactory.WebMVC.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ICustomersService _customersService;

        public CustomerController(ICustomersService customersService)
        {
            _customersService = customersService;
        }
    }
}

src/api/PromoCodeFactory/PromoCodeFactory.WebMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PromoCodeFactory.WebMVC.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace PromoCodeFactory.WebMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/api/PromoCodeFactory/PromoCodeFactory.WebMVC/Controllers/PreferenceController.cs
using Microsoft.AspNetCore.Mvc;
using PromocodeFactory.BusinessLogic.Models.DTO.Request.PromoCodeManagement;
using PromoCodeFactory.BusinessLogic.Interfaces.PromoCodeManagementServices;
using System;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;

namespace PromoCodeFactory.WebMVC.Controllers
{
    public class PreferenceController : Controller
    {
        private readonly IPreferencesService _preferencesService;

        public PreferenceController(IPreferencesService preferencesService)
        {
            _preferencesService = preferencesService;
        }

        [HttpGet]
        public async Task<IActionResult> IndexAsync()
        {
            return View("Index", await _preferencesService.GetAllAsync());
        }

        [HttpPost]
        public async Task<IActionResult> AddAsync(PreferenceDtoRequest model)
        {
            var response = await _preferencesService.AddAsync(model);

            return View("Index", await _preferencesService.GetAllAsync());
        }

        [HttpPost("{id:guid}")]
        public async Task<IActionResult> DeleteAsync([Required] Guid id)
        {
            await _preferencesService.DeleteAsync(id);

            return View("Index", await _preferencesService.GetAllAsync());
        }

        [HttpPost("{id:guid}")]
        public async Task<IActionResult> UpdateAsync([Required] Guid id, PreferenceDtoRequest model)
        {
            await _preferencesService.UpdateAsync(model);

            return View("Index", await _preferencesService.GetAllAsync());
        }

        [HttpGet("{id:guid}")]
        public async Task<IActionResult> UpdateAsync([Required] Guid id)
        {
            var preference = await _preferencesService.GetByIdAsync(id);

            return View("Update", preference);
        }
    }
}

src/api/PromoCodeFactory/PromoCodeFactory.WebMVC/Controllers/PromoCodeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PromoCodeFactory.BusinessLogic.Interfaces.PromoCodeManagementServices;

namespace PromoCodeFactory.WebMVC.Controllers
{
    public class PromoCodeController : Controller
    {
        private readonly IPromoCodesServices _promoCodesServices;

        public PromoCodeController(IPromoCodesServices promoCodesServices)
        {
            _promoCodesServices = promoCodesServices;
        }
    }
}

src/api/PromoCodeFactory/PromoCodeFactory.WebMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/api/PromoCodeFactory/PromoCodeFactory.WebMVC/Views/Preference/Index.cshtml
@using PromocodeFactory.BusinessLogic.Models.DTO.Request.PromoCodeManagement
@using System.Linq
@model IEnumerable<PromoCodeFactory.BusinessLogic.Models.DTO.Response.PromoCodeManagement.Preferences.PreferenceDtoResponse>

@{
    Layout = "_Layout";
    ViewData["Title"] = "Предпочтения";
}

<h1>Предпочтения</h1>

@{
    var preferenceDto = new PreferenceDtoRequest();
}

<div class="row">
    <div class="col-md-4">
        <form method="post" asp-action="Add">
            <div class="form-group">
                <input asp-for="@preferenceDto.Id" class="form-control" hidden=""/>
            </div>

            <div class="form-group">
                <label asp-for="@preferenceDto.Name" class="control-label"></label>
                <input name="Name" class="form-control"/>
                <span asp-validation-for="@preferenceDto.Name" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Добавить" class="btn btn-primary">
            </div>
        </form>
    </div>
</div>

<div class="col-md-10">
    <table class="table">
        <thead>
        <tr>
            <th>Идентификатор</th>
            <th>Наименование</th>
            <th></th>
            <th></th>
        </tr>
        </thead>

        <tbody>
        @foreach (var preference in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(x => preference.Id)
                </td>

                <td>
                    @Html.DisplayFor(x => preference.Name)
                </td>

                <td>
                    <button type="button" class="btn btn-info" asp-action="Update" asp-route-id="@preference.Id">Редактировать</button>
                </td>

                <td>
                    <form method="post">
                        <input type="submit" value="Удалить" class="btn btn-danger" asp-action="Delete" asp-route-id="@preference.Id" />
                    </form>
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>

src/api/PromoCodeFactory/PromoCodeFactory.WebMVC/Views/Preference/Update.cshtml
@using PromocodeFactory.BusinessLogic.Models.DTO.Request.PromoCodeManagement
@using System.Linq
@model PromoCodeFactory.BusinessLogic.Models.DTO.Response.PromoCodeManagement.Preferences.PreferenceDtoResponse

@{
    Layout = "_Layout";
    ViewData["Title"] = "Изменение наименования предпочтения";
}

<h1>Изменение наименования предпочтения</h1>

@{
    var preferenceDto = new PreferenceDtoRequest();
}

<form method="post">
    <input type="submit" class="btn btn-success" value="Сохранить">
    <input type="submit" class="btn btn-block" value="Назад">
</form>

src/api/PromoCodeFactory/PromoCodeFactory.WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PromoCodeFactory.WebMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Админ</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Preference" asp-action="Index">Предпочтения</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PromoCode" asp-action="Index">Промокоды</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Пользователи</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - PromoCodeFactory.WebMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>